q1 = "🔸1/15🔸\n" + "I feel run down and drained of physical or emotional energy."
q2 = "🔸2/15🔸\n" + "I have negative thoughts about my job."
q3 = "🔸3/15🔸\n" + "I am harder and less sympathetic with people than perhaps they deserve."
q4 = "🔸4/15🔸\n" + "I am easily irritated by small problems, or by my co-workers."
q5 = "🔸5/15🔸\n" + "I feel misunderstood or unappreciated by my co-workers."
q6 = "🔸6/15🔸\n" + "I feel that I have no one to talk to."
q7 = "🔸7/15🔸\n" + "I feel that I am achieving less than I should."
q8 = "🔸8/15🔸\n" + "I feel under an unpleasant level of pressure to succeed. "
q9 = "🔸9/15🔸\n" + "I feel that I am not getting what I want out of my job."
q10 = "🔸10/15🔸\n" + "I feel that I am in the wrong organization or profession."
q11 = "🔸11/15🔸\n" + "I am frustrated with parts of my job."
q12 = "🔸12/15🔸\n" + "I feel that organizational politics or bureaucracy frustrate my ability to do a good job."
q13 = "🔸13/15🔸\n" + "I feel that there is more work to do than I practically have the ability to do."
q14 = "🔸14/15🔸\n" + "I feel that I do not have time to do many of the things that are important to doing a good quality job."
q15 = "🔸15/15🔸\n" + "I find that I do not have time to plan as much as I want to."

